Repository Netcracker/qubership-nifi-registry, pull requests merged in 2025-02, with the labels that each got.

#1 feat(ci): Added common workflows.
  .github/auto-labeler-config.yaml
  .github/release-drafter-config.yml
  .github/workflows/automatic-pr-labeler.yaml
  .github/workflows/cla.yaml
  .github/workflows/pr-conventional-commits.yaml
  .github/workflows/pr-lint-title.yaml
  .github/workflows/prettier.yaml
  .github/workflows/profanity-filter.yaml
Labels: enhancement

#3 feat(ci): add artifacts copy to top
  nifi-registry-assembly/pom.xml
  pom.xml
Labels: enhancement

#4 feat(ci): Use super-linter instead of prettier
  .github/workflows/prettier.yaml
  .github/workflows/super-linter.yml
  Dockerfile
Labels: bug, enhancement

#5 feat: Add GitHub Actions workflow for Maven release and Docker image upload
  .github/workflows/maven-release.yaml
  nifi-registry-db-util/pom.xml
  pom.xml
Labels: enhancement

#6 fix: change script name
  nifi-scripts/common.sh
  nifi-scripts/connect_to_db.sh
  nifi-scripts/custom_oidc_secure.sh
  nifi-scripts/logging_api.sh
  nifi-scripts/pre_secure.sh
  nifi-scripts/start.sh
  nifi-scripts/update_bundle_provider.sh
  nifi-scripts/update_flow_provider.sh
Labels: bug

#8 feat(ci): configure maven publish
  pom.xml
Labels: enhancement
