Repository Netcracker/qubership-nifi-registry, pull requests merged in 2025-03, with the labels that each got.

#9 fix: fixed shellcheck errors
  nifi-scripts/common.sh
  nifi-scripts/connect_to_db.sh
  nifi-scripts/custom_oidc_secure.sh
  nifi-scripts/logging_api.sh
  nifi-scripts/pre_secure.sh
  nifi-scripts/start.sh
  nifi-scripts/update_bundle_provider.sh
  nifi-scripts/update_flow_provider.sh
Labels: bug

#10 feat(ci): add PR auto-assignment workflow and configuration
  .github/pr-assigner-config.yml
  .github/workflows/pr-assigner.yml
Labels: enhancement

#11 feat(ci): add cdxgen and pr collect commit msgs wfs
  .github/linters/.jscpd.json
  .github/linters/.sqlfluff
  .github/linters/actionlint.yml
  .github/linters/sun_checks.xml
  .github/workflows/cdxgen.yaml
  .github/workflows/pr-collect-commit-messages.yaml
  .github/workflows/super-linter.yml
Labels: enhancement

#12 fix: fix linter issues
  .github/linters/sun_checks.xml
  .github/workflows/pr-assigner.yml
  .sqlfluffignore
  README.md
  nifi-registry-util/src/main/java/org/qubership/cloud/nifi/registry/util/DbManager.java
  nifi-registry-util/src/main/java/org/qubership/cloud/nifi/registry/util/NiFiRegistryUtilApplication.java
Labels: bug

#13 feat(ci): replace revision property with hard-coded version
  nifi-registry-assembly/pom.xml
  nifi-registry-db-util/pom.xml
  nifi-registry-migration-util/pom.xml
  nifi-registry-util/pom.xml
  pom.xml
Labels: enhancement

#15 test(ci): add nifi registry autotests
  .github/actions/run-newman-tests/action.yml
  .github/actions/run-nifi-reg-tests-plain/action.yml
  .github/actions/run-nifi-reg-tests-tls-db/action.yml
  .github/actions/run-nifi-reg-tests-tls/action.yml
  .github/collections/NiFi_Reg_AT.json.postman_environment
  .github/collections/NiFi_Reg_AT_TLS.json.postman_environment
  .github/collections/NiFi_Registry_API_Tests.postman_collection.json
  .github/docker/plain/docker-compose.yaml
  .github/docker/tls-db/docker-compose.yaml
  .github/docker/tls/docker-compose.yaml
  .github/workflows/docker-build-and-test.yml
  .github/workflows/maven-build-and-test.yml
  .github/workflows/sh/nifi-gen-certs.sh
  .github/workflows/sh/nifi-lib.sh
  nifi-scripts/start.sh
Labels: bug, enhancement
